routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
	
	if(\Auth::check()){
		return redirect("/competition");
	}else{
		return redirect("/register");
	}
	
});

Route::get('/admin', function (){
    return redirect("/questions");
});

Route::resource("tweets","TweetController");
Route::resource("offices","OfficeController"); 
Route::get('/search_office', 'OfficeController@search_office');
Route::resource("answers","AnswerController"); 
Route::resource("questions","QuestionController"); 

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/help', 'HomeController@help');
Route::get('/test', 'HomeController@test')->name('test');
Route::get('/competition', 'CompetitionController@competition')->name('competition');
Route::post('/send_answer', 'CompetitionController@send_answer');
Route::get('/finish', 'CompetitionController@finish');
Route::get('/final_result', 'CompetitionController@final_result');
Route::get('/top', 'CompetitionController@top');

Route::get('/list_users', 'AdminController@list_users');
Route::get('/search_user', 'AdminController@search_user');
Route::get('/user_detail/{id}', 'AdminController@user_detail');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Question;

class Answer extends Model
{
    //
	public function question()
	{
	        return $this->belongsTo('App\Question');
	}
	
	public function rate_answer($answer_id,$question_id){
		
		
		
		if(isset($id)){
			$answer = Answer::findOrFail($id);
			return $answer;
		}else{
			
		}
	}
}

app/Http/Controllers/AnswerController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\View;
use App\Answer;
use App\Question;
use Illuminate\Http\Request;

class AnswerController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	
	public function __construct()
	{
	    View::share('viewsw', 'answers'); 
		$this->middleware('auth.admin');
	}
	
	public function index()
	{
		$answers = Answer::orderBy('id', 'desc')->paginate(10);

		return view('answers.index', compact('answers'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$questions = Question::orderBy('id', 'asc')->get();
		return view('answers.create',compact('questions'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$answer = new Answer();

		$answer->content = $request->input("content");
        $answer->question_id = $request->input("question_id");
        $answer->valid = $request->input("valid");

		$answer->save();

		return redirect()->route('questions.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$answer = Answer::findOrFail($id);
		
		return view('answers.show', compact('answer'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$questions = Question::orderBy('id', 'asc')->get();
		$answer = Answer::findOrFail($id);

		return view('answers.edit', compact('answer','questions'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$answer = Answer::findOrFail($id);

		$answer->content = $request->input("content");
        $answer->question_id = $request->input("question_id");
        $answer->valid = $request->input("valid");

		$answer->save();

		return redirect()->route('questions.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$answer = Answer::findOrFail($id);
		$answer->delete();

		return redirect()->route('questions.index')->with('message', 'Item created successfully.');
	}

}

resources/views/answers/create.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> New Answer</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('answers.store') }}" method="POST">
               
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

				 <label for="content-field">Questions</label>
				<select class="form-control" name="question_id">
    
				  @foreach ($questions as $question)
				    <option value="{{ $question->id }}"> 
				        {{ $question->content }} 
				    </option>
				  @endforeach    
				</select>
				<br />

                <div class="form-group @if($errors->has('content')) has-error @endif">
                       <label for="content-field">Content</label>
                    <textarea class="form-control" id="content-field" rows="3" name="content"></textarea>
                       @if($errors->has("content"))
                        <span class="help-block">{{ $errors->first("content") }}</span>
                       @endif
                    </div>
                    
                    <div class="form-group @if($errors->has('valid')) has-error @endif">
                       
					<input type="checkbox" name="valid" value=""> Valid
					<br /><br />
					
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('answers.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/answers/edit.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Answers / Edit #{{$answer->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('answers.update', $answer->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

				 <label for="content-field">Questions</label>
				<select class="form-control" name="question_id">
    
				  @foreach ($questions as $question)
				    <option value="{{ $question->id }}" {{ ( $question->id == $answer->question_id) ? 'selected' : '' }}> 
				        {{ $question->content }} 
				    </option>
				  @endforeach    
				</select>
				<br />

                <div class="form-group @if($errors->has('content')) has-error @endif">
                       <label for="content-field">Content</label>
                    <textarea class="form-control" id="content-field" rows="3" name="content">{{ is_null(old("content")) ? $answer->content : old("content") }}</textarea>
                       @if($errors->has("content"))
                        <span class="help-block">{{ $errors->first("content") }}</span>
                       @endif
                    </div>
                    
                    <div class="form-group @if($errors->has('valid')) has-error @endif">
                     
					 @if($answer->valid)
						<input type="checkbox" name="valid" value="1" checked> Valid
					@else
						<input type="checkbox" name="valid" value="1"> Valid
					@endif
					<br /><br />
					
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('answers.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/answers/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Answers
            <a class="btn btn-success pull-right" href="{{ route('answers.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($answers->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>CONTENT</th>
                        <th>QUESTION_ID</th>
                        <th>VALID</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($answers as $answer)
                            <tr>
                                <td>{{$answer->id}}</td>
                                <td>{{$answer->content}}</td>
                    <td>{{$answer->question_id}}</td>
                    <td>{{$answer->valid}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('answers.show', $answer->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('answers.edit', $answer->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('answers.destroy', $answer->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $answers->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/answers/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Answers / Show #{{$answer->id}}</h1>
        <form action="{{ route('answers.destroy', $answer->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('answers.edit', $answer->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="content">CONTENT</label>
                     <p class="form-control-static">{{$answer->content}}</p>
                </div>
                    <div class="form-group">
                     <label for="question_id">QUESTION_ID</label>
                     <p class="form-control-static">{{$answer->question_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="valid">VALID</label>
                     <p class="form-control-static">{{$answer->valid}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('answers.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection