routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
	
	if(\Auth::check()){
		return redirect("/competition");
	}else{
		return redirect("/register");
	}
	
});

Route::get('/admin', function (){
    return redirect("/questions");
});

Route::resource("tweets","TweetController");
Route::resource("offices","OfficeController"); 
Route::get('/search_office', 'OfficeController@search_office');
Route::resource("answers","AnswerController"); 
Route::resource("questions","QuestionController"); 

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/help', 'HomeController@help');
Route::get('/test', 'HomeController@test')->name('test');
Route::get('/competition', 'CompetitionController@competition')->name('competition');
Route::post('/send_answer', 'CompetitionController@send_answer');
Route::get('/finish', 'CompetitionController@finish');
Route::get('/final_result', 'CompetitionController@final_result');
Route::get('/top', 'CompetitionController@top');

Route::get('/list_users', 'AdminController@list_users');
Route::get('/search_user', 'AdminController@search_user');
Route::get('/user_detail/{id}', 'AdminController@user_detail');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;
use App\Answer;
use App\Result;
use DB;

class Question extends Model
{
	//
	public function answers()
	{
		return $this->hasMany('App\Answer');
	}
	
	public function results()
	{
		return $this->hasMany('App\Result');
	}
	
	public function answer_letters(){
		return ["a","b","c","d"];
	}
	
	public function get_valid_answer(){
		
		$answer = Answer::where("question_id",$this->id)->where('valid', true)->first();
		return $answer;
		
	}
	
	public function get_valid_answer_id(){
		
		$answer = Answer::where("question_id",$this->id)->where('valid', true)->first();
		if(isset($answer)){
			return $answer->id;
		}else{
			return 0;
		}
		
	}
	
	public function get_valid_answer_ids(){
		
		$answers = Answer::orderBy('id', 'desc')->where("question_id",$this->id)->where('valid', true)->get();
		$answers_ids = $answers->pluck('id')->toArray();
		return $answers_ids;
		
	}
	
	public function rate($user_id,$user_answer_id,$final_answer=null,$answer_content=null){
		
		//Log::info("Final question: $final_answer");
		
		$result = Result::get_result($user_id,$this->id);
		
		if($this->type == "complete"){
			$result->answer_ids = $final_answer;
			if($this->winning_combination == $final_answer){
				$result->valid = true;
			}else{
				$result->valid = false;
			}
		}else if($this->type =="yes_or_no"){
			
			//Compare answers
			$result = Result::get_result($user_id,$this->id);
			$result->answer_id = $user_answer_id;
			if($user_answer_id == $this->get_valid_answer_id()){
				$result->valid = true;
			}else{
				$result->valid = false;
			}
			$result->content = $answer_content;
			$result->answer_id = $user_answer_id;
			
		}else if($this->type =="multiple_choice"){
			//Compare answers
			$result = Result::get_result($user_id,$this->id);
			$result->answer_id = $user_answer_id;
			if($user_answer_id == $this->get_valid_answer_id()){
				$result->valid = true;
			}else{
				$result->valid = false;
			}
			
		}else if($this->type =="multiple_choices"){
			//Get valid answers ids
			$valid_answers = $this->get_valid_answer_ids();
			//Compare answers
			$result = Result::get_result($user_id,$this->id);
			$result->answer_ids = $user_answer_id;
			$user_answers = explode(",", $user_answer_id);

			//sort($user_answers);
			sort($valid_answers);
			
			Log::info("valid_answers:");
			Log::info($valid_answers);
			
			Log::info("user_answers:");
			Log::info($user_answers);
			
			$user_answers = array_unique($user_answers);
			sort($user_answers);
			
			Log::info("user_answers despues de array_unique:");
			Log::info($user_answers);
			
			if($user_answers == $valid_answers){
				$result->valid = true;
			}else{
				$result->valid = false;
			}
		}else if($this->type =="complete_with_content"){
			$result = Result::get_result($user_id,$this->id);
			$result->content = $answer_content;
			$result->valid = true;
		}
		
		$result->save();
		return $result;
	}
	
	
	/*
			  <option value="complete">complete</option>
			  <option value="yes_or_no">yes_or_no</option>
			  <option value="multiple_choices">multiple_choices</option>
			  <option value="complete_with_content">complete_with_content</option>
	*/
	
	public function is_complete(){
		if($this->type == "complete"){
			return true;
		}else{
			return false;
		}
	}
	
	public function is_yes_or_no(){
		if($this->type == "yes_or_no"){
			return true;
		}else{
			return false;
		}
	}
	
	public function is_multiple_choice(){
		if($this->type == "multiple_choice"){
			return true;
		}else{
			return false;
		}
	}
	
	public function is_multiple_choices(){
		if($this->type == "multiple_choices"){
			return true;
		}else{
			return false;
		}
	}
	
	public function is_complete_with_content(){
		if($this->type == "complete_with_content"){
			return true;
		}else{
			return false;
		}
	}
	
	public static function get_last_answered_question($user_id){
		$question = DB::table('questions')
		                     ->select(DB::raw('questions.id, results.valid, results.user_id'))
							 ->join('results', 'questions.id', '=', 'results.question_id')
							 ->where("user_id",$user_id)
							 ->orderBy('id', 'desc')
							 ->get()
							 ->first();
		return $question;
	}
	
	
}

app/Http/Controllers/QuestionController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\View;
use App\Question;
use Illuminate\Http\Request;

class QuestionController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	
	public function __construct()
	{
		//$this->middleware('auth');
		
	    View::share('viewsw', 'questions'); 
		$this->middleware('auth.admin');
	}
	
	public function index()
	{
		$questions = Question::orderBy('id', 'asc')->paginate(15);

		return view('questions.index', compact('questions'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('questions.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$question = new Question();

		$question->content = $request->input("content");
        $question->type = $request->input("type");
		$question->winning_combination = $request->input("winning_combination");

		$question->save();

		return redirect()->route('questions.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$question = Question::findOrFail($id);

		return view('questions.show', compact('question'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$question = Question::findOrFail($id);

		return view('questions.edit', compact('question'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$question = Question::findOrFail($id);

		$question->content = $request->input("content");
        $question->type = $request->input("type");
		$question->winning_combination = $request->input("winning_combination");

		$question->save();

		return redirect()->route('questions.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$question = Question::findOrFail($id);
		$question->delete();

		return redirect()->route('questions.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/questions/create.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Questions / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('questions.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
				
				<label for="type-field">Type</label> <br />
				<select name="type">
				  <option value="complete">complete</option>
				  <option value="yes_or_no">yes_or_no</option>
				  <option value="multiple_choices">multiple_choices</option>
				  <option value="complete_with_content">complete_with_content</option>
				</select>
				<br /><br />
                <div class="form-group @if($errors->has('content')) has-error @endif">
                       <label for="content-field">Content</label>
                    <textarea class="form-control" id="content-field" rows="3" name="content">{{ old("content") }}</textarea>
                       @if($errors->has("content"))
                        <span class="help-block">{{ $errors->first("content") }}</span>
                       @endif
                    </div>
                    
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('questions.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/questions/edit.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Questions / Edit #{{$question->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('questions.update', $question->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('content')) has-error @endif">
                       <label for="content-field">Content</label>
                    <textarea class="form-control" id="content-field" rows="3" name="content">{{ is_null(old("content")) ? $question->content : old("content") }}</textarea>
                       @if($errors->has("content"))
                        <span class="help-block">{{ $errors->first("content") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('type')) has-error @endif">
                       <label for="type-field">Type</label>
                    <input type="text" id="type-field" name="type" class="form-control" value="{{ is_null(old("type")) ? $question->type : old("type") }}"/>
                       @if($errors->has("type"))
                        <span class="help-block">{{ $errors->first("type") }}</span>
                       @endif
                    </div>
					
                    <div class="form-group @if($errors->has('type')) has-error @endif">
                       <label for="type-field">Winning Combination</label>
                    <input type="text" id="winning_combination-field" name="winning_combination" class="form-control" value="{{$question->winning_combination}}"/>
                       @if($errors->has("winning_combination"))
                        <span class="help-block">{{ $errors->first("winning_combination") }}</span>
                       @endif
                    </div>
					
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('questions.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/questions/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Questions
            <a class="btn btn-success pull-right" href="{{ route('questions.create') }}"><i class="glyphicon glyphicon-plus"></i> Create Question</a> <br />
			
			<a class="btn btn-success pull-right" href="{{ route('answers.create') }}"><i class="glyphicon glyphicon-plus"></i> Create Answer</a>
			
        </h1>
		
		

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
			
			
			
			
            @if($questions->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th witdth="10%">ID</th>
                            <th witdth="30%">CONTENT</th>
                        	<th witdth="10%">TYPE</th>
							<th witdth="10%">WINNING COMBINATION</th>
                            <th witdth="40%">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($questions as $question)
                            <tr>
                                <td>{{$question->id}}</td>
                                <td>{!!$question->content!!}</td>
                    			<td>{{$question->type}}</td>
								<td>{{$question->winning_combination}}</td>
                                <td class="text-right">
                                    
                                    <a class="btn btn-xs btn-warning" href="{{ route('questions.edit', $question->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('questions.destroy', $question->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
							
		                    <thead>
		                        <tr>
									<th></th>
		                            <th colspan="1">ANSWER</th>
		                            <th>INDEX</th>
									<th>VALID</th>
									<th>OPTIONS</th>
							</thead>
							
							 @foreach($question->answers()->get() as $answer)
								<tr>
									<td></td>
								    <td colspan="1">{{$answer->content}}</td>
									<td>{{$answer->index}}</td>
									<td>{{$answer->valid}}</td>
                                    <td><a class="btn btn-xs btn-warning" href="{{ route('answers.edit', $answer->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('answers.destroy', $answer->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form></td>
								 </tr>
							 @endforeach
							
							
                        @endforeach
                    </tbody>
                </table>
                {!! $questions->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/questions/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Questions / Show #{{$question->id}}</h1>
        <form action="{{ route('questions.destroy', $question->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('questions.edit', $question->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="content">CONTENT</label>
                     <p class="form-control-static">{{$question->content}}</p>
                </div>
                    <div class="form-group">
                     <label for="type">TYPE</label>
                     <p class="form-control-static">{{$question->type}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('questions.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection