routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
	
	if(\Auth::check()){
		return redirect("/competition");
	}else{
		return redirect("/register");
	}
	
});

Route::get('/admin', function (){
    return redirect("/questions");
});

Route::resource("tweets","TweetController");
Route::resource("offices","OfficeController"); 
Route::get('/search_office', 'OfficeController@search_office');
Route::resource("answers","AnswerController"); 
Route::resource("questions","QuestionController"); 

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/help', 'HomeController@help');
Route::get('/test', 'HomeController@test')->name('test');
Route::get('/competition', 'CompetitionController@competition')->name('competition');
Route::post('/send_answer', 'CompetitionController@send_answer');
Route::get('/finish', 'CompetitionController@finish');
Route::get('/final_result', 'CompetitionController@final_result');
Route::get('/top', 'CompetitionController@top');

Route::get('/list_users', 'AdminController@list_users');
Route::get('/search_user', 'AdminController@search_user');
Route::get('/user_detail/{id}', 'AdminController@user_detail');

app/Office.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB; 

class Office extends Model
{
    //
	public function users()
	{
		return $this->hasMany('App\User');
	}
	
	public function get_rating_info($field){
		$office = DB::table('users')
		                     ->select(DB::raw('offices.id, offices.members, offices.name, AVG(ratings.rating) AS average, Count(users.id) as answered'))
							 ->join('offices', 'offices.id', '=', 'users.office_id')
							 ->join('ratings', 'ratings.user_id', '=', 'users.id')
							 ->where("offices.id",$this->id)
							 ->groupBy('id')
							 ->orderBy('average', 'desc')
							 ->get()
							 ->first();
		
		if(isset($office)){
			if($field == "average"){
				return $office->average;
			}else if($field == "answered"){
				return $office->answered;
			}
		}
		
	}
	
}

app/Http/Controllers/OfficeController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\View;
use App\Office;
use Illuminate\Http\Request;
use DB;
use Illuminate\Support\Facades\Input;

class OfficeController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	
	public function __construct()
	{
	    View::share('viewsw', 'offices'); 
		$this->middleware('auth.admin');
	}
	
	public function index()
	{
		//$offices = Office::orderBy('id', 'desc')->paginate(50);
		/*

		
		SELECT o.id, o.members, o.name, AVG(r.rating) AS AverageRating FROM users INNER JOIN offices as o ON o.id = users.office_id INNER JOIN ratings as r ON r.user_id = users.id GROUP BY o.id
		
		*/
		
		$offices = DB::table('users')
		                     ->select(DB::raw('offices.id, offices.members, offices.name, AVG(ratings.rating) AS average, Count(users.id) as answered'))
							 ->join('offices', 'offices.id', '=', 'users.office_id')
							 ->join('ratings', 'ratings.user_id', '=', 'users.id')
							 ->groupBy('offices.id')
							 ->orderBy('average', 'desc')
							 ->get();
		
		return view('offices.index', compact('offices'));
	}
	
	public function search_office(){
		
		$param = Input::get('param');
		$offices = DB::table('users')
		                     ->select(DB::raw('offices.id, offices.members, offices.name, AVG(ratings.rating) AS average, Count(users.id) as answered'))
							 ->join('offices', 'offices.id', '=', 'users.office_id')
							 ->join('ratings', 'ratings.user_id', '=', 'users.id')
							 ->groupBy('id')
							 ->where("offices.name","like","%".$param."%")
							 ->orderBy('average', 'desc')
							 ->get();
		
		return view('offices.search_office', compact('offices'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('offices.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$office = new Office();

		$office->members = $request->input("members");
        $office->name = $request->input("name");

		$office->save();

		return redirect()->route('offices.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$office = Office::findOrFail($id);
		$users = $office->users()->get();
		return view('offices.show', compact('office','users'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$office = Office::findOrFail($id);
		return view('offices.edit', compact('office'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$office = Office::findOrFail($id);

		$office->members = $request->input("members");
        $office->name = $request->input("name");

		$office->save();

		return redirect()->route('offices.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$office = Office::findOrFail($id);
		$office->delete();

		return redirect()->route('offices.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/offices/create.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Offices / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('offices.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('members')) has-error @endif">
                       <label for="members-field">Members</label>
                    <input type="text" id="members-field" name="members" class="form-control" value="{{ old("members") }}"/>
                       @if($errors->has("members"))
                        <span class="help-block">{{ $errors->first("members") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('offices.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/offices/edit.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Offices / Edit #{{$office->id}}</h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('offices.update', $office->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('members')) has-error @endif">
                       <label for="members-field">Members</label>
                    <input type="text" id="members-field" name="members" class="form-control" value="{{ is_null(old("members")) ? $office->members : old("members") }}"/>
                       @if($errors->has("members"))
                        <span class="help-block">{{ $errors->first("members") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('name')) has-error @endif">
                       <label for="name-field">Name</label>
                    <input type="text" id="name-field" name="name" class="form-control" value="{{ is_null(old("name")) ? $office->name : old("name") }}"/>
                       @if($errors->has("name"))
                        <span class="help-block">{{ $errors->first("name") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('offices.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/offices/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Offices
            <a class="btn btn-success pull-right" href="{{ route('offices.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')

    <div class="row">
		<form action="/search_office" method="GET">
			
       	 	<div class="col-md-6">
				<input type="text" id="param-field" name="param" class="form-control" placeholder="Search by office"/>
			</div>
		
        	<div class="col-md-6">
				<button type="submit" class="btn btn-primary">Search</button>
			</div>
			
			<br /><br /><br />
			
		</form>	
	</div>
	

    <div class="row">
        <div class="col-md-12">
           
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>MEMBERS</th>
							<th>ANSWERED</th>
                       	 	<th>NAME</th>
							<th>RATING</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($offices as $office)
                            <tr>
                                <td>{{$office->id}}</td>
                                <td>{{$office->members}}</td>
								<td>{{$office->answered}}</td>
                    			<td>{{$office->name}}</td>
								<td>{{$office->average}}</td>
                                <td class="text-right">
                                    
									<a class="btn btn-xs btn-primary" href="{{ route('offices.show', $office->id) }}"><i class="glyphicon glyphicon-eye-open"></i> Show</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('offices.edit', $office->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('offices.destroy', $office->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
               

        </div>
    </div>

@endsection

resources/views/offices/search_office.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Offices
            <a class="btn btn-success pull-right" href="{{ route('offices.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')

    <div class="row">
		<form action="/search_office" method="GET">
			
       	 	<div class="col-md-6">
				<input type="text" id="param-field" name="param" class="form-control" placeholder="Search by office"/>
			</div>
		
        	<div class="col-md-6">
				<button type="submit" class="btn btn-primary">Search</button>
			</div>
			
			<br /><br /><br />
			
		</form>	
	</div>
	

    <div class="row">
        <div class="col-md-12">
           
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>MEMBERS</th>
							<th>ANSWERED</th>
                       	 	<th>NAME</th>
							<th>RATING</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($offices as $office)
                            <tr>
                                <td>{{$office->id}}</td>
                                <td>{{$office->members}}</td>
								<td>{{$office->answered}}</td>
                    			<td>{{$office->name}}</td>
								<td>{{$office->average}}</td>
                                <td class="text-right">
                                    
									<a class="btn btn-xs btn-primary" href="{{ route('offices.show', $office->id) }}"><i class="glyphicon glyphicon-eye-open"></i> Show</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('offices.edit', $office->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('offices.destroy', $office->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
               

        </div>
    </div>

@endsection

resources/views/offices/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Offices / Show #{{$office->id}}</h1>
        <form action="{{ route('offices.destroy', $office->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('offices.edit', $office->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')


    <div class="row">
        <div class="col-md-6">
			
            <div class="form-group">
                 <label for="members">MEMBERS</label>
                 <h1>{{$office->members}}</h1>
            </div>
                <div class="form-group">
                 <label for="name">NAME</label>
                 <h1>{{$office->name}}</h1>
            </div>
		</div>
		
        <div class="col-md-6">
			
            <div class="form-group">
                 <label for="members">ANSWERED</label>
				 <h1>{{$office->get_rating_info("answered")}}</h1>
            </div>
			
            <div class="form-group">
                 <label for="members">AVERAGE</label>
				 <h1>{{$office->get_rating_info("average")}}</h1>
            </div>
			
          
		</div>
		
	</div>


    <div class="row">
        <div class="col-md-12">

		            @if($users->count())
		                <table class="table table-condensed table-striped">
		                    <thead>
		                        <tr>
		                            <th>EMPLOYEE NUMBER</th> 
		                       	 	<th>NAME</th>
								 <th>OFFICE</th>
								 <th>RATING</th>
		                         <th>DETAILS</th>
		                        </tr>
		                    </thead>

		                    <tbody>
		                        @foreach($users as $user)
		                            <tr>
		                                <td>{{$user->employee_number}}</td>
		                   			 	<td>{{$user->name}}</td>
										<td>@if(isset($user->office)){{$user->office->name}}@endif</td>
										<td>{{$user->get_test_rating()}}</td>	
		                                <td><a class="btn btn-xs btn-primary" href="/user_detail/{{$user->id}}">show</a></td>
		                            </tr>
		                        @endforeach
		                    </tbody>
		                </table>
		             
		            @else
		                <h3 class="text-center alert alert-info">Empty!</h3>
		            @endif

		    

            <a class="btn btn-link" href="{{ route('offices.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection